// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	Snapshot
	Mainchain
	Rollback
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Snapshot represents a snapshot of the blockchain, including the state
// tree and issuance memory.
type Snapshot struct {
	// Nodes contains every node within the state tree, including interior nodes.
	// The nodes are ordered according to a pre-order traversal.
	Nodes []*Snapshot_StateTreeNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	// Nonces contains the record of recent nonces for ensuring
	// uniqueness of issuances.
	Nonces []*Snapshot_Nonce `protobuf:"bytes,2,rep,name=nonces" json:"nonces,omitempty"`
}

func (m *Snapshot) Reset()                    { *m = Snapshot{} }
func (m *Snapshot) String() string            { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()               {}
func (*Snapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Snapshot) GetNodes() []*Snapshot_StateTreeNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Snapshot) GetNonces() []*Snapshot_Nonce {
	if m != nil {
		return m.Nonces
	}
	return nil
}

type Snapshot_Nonce struct {
	Hash     []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ExpiryMs uint64 `protobuf:"varint,2,opt,name=expiry_ms,json=expiryMs" json:"expiry_ms,omitempty"`
}

func (m *Snapshot_Nonce) Reset()                    { *m = Snapshot_Nonce{} }
func (m *Snapshot_Nonce) String() string            { return proto.CompactTextString(m) }
func (*Snapshot_Nonce) ProtoMessage()               {}
func (*Snapshot_Nonce) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Snapshot_Nonce) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Snapshot_Nonce) GetExpiryMs() uint64 {
	if m != nil {
		return m.ExpiryMs
	}
	return 0
}

type Snapshot_StateTreeNode struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Snapshot_StateTreeNode) Reset()                    { *m = Snapshot_StateTreeNode{} }
func (m *Snapshot_StateTreeNode) String() string            { return proto.CompactTextString(m) }
func (*Snapshot_StateTreeNode) ProtoMessage()               {}
func (*Snapshot_StateTreeNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Snapshot_StateTreeNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// Mainchain represents a mainchain of the blockchain
type Mainchain struct {
	Hashs []*Mainchain_Hash `protobuf:"bytes,1,rep,name=hashs" json:"hashs,omitempty"`
}

func (m *Mainchain) Reset()                    { *m = Mainchain{} }
func (m *Mainchain) String() string            { return proto.CompactTextString(m) }
func (*Mainchain) ProtoMessage()               {}
func (*Mainchain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Mainchain) GetHashs() []*Mainchain_Hash {
	if m != nil {
		return m.Hashs
	}
	return nil
}

type Mainchain_Hash struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Mainchain_Hash) Reset()                    { *m = Mainchain_Hash{} }
func (m *Mainchain_Hash) String() string            { return proto.CompactTextString(m) }
func (*Mainchain_Hash) ProtoMessage()               {}
func (*Mainchain_Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Mainchain_Hash) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// Rollback contained a detach list and a attach list for orphan block rollback
type Rollback struct {
	Detach []*Rollback_Hash `protobuf:"bytes,1,rep,name=detach" json:"detach,omitempty"`
	Attach []*Rollback_Hash `protobuf:"bytes,2,rep,name=attach" json:"attach,omitempty"`
}

func (m *Rollback) Reset()                    { *m = Rollback{} }
func (m *Rollback) String() string            { return proto.CompactTextString(m) }
func (*Rollback) ProtoMessage()               {}
func (*Rollback) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Rollback) GetDetach() []*Rollback_Hash {
	if m != nil {
		return m.Detach
	}
	return nil
}

func (m *Rollback) GetAttach() []*Rollback_Hash {
	if m != nil {
		return m.Attach
	}
	return nil
}

type Rollback_Hash struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Rollback_Hash) Reset()                    { *m = Rollback_Hash{} }
func (m *Rollback_Hash) String() string            { return proto.CompactTextString(m) }
func (*Rollback_Hash) ProtoMessage()               {}
func (*Rollback_Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Rollback_Hash) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*Snapshot)(nil), "chain.core.txdb.internal.storage.Snapshot")
	proto.RegisterType((*Snapshot_Nonce)(nil), "chain.core.txdb.internal.storage.Snapshot.Nonce")
	proto.RegisterType((*Snapshot_StateTreeNode)(nil), "chain.core.txdb.internal.storage.Snapshot.StateTreeNode")
	proto.RegisterType((*Mainchain)(nil), "chain.core.txdb.internal.storage.Mainchain")
	proto.RegisterType((*Mainchain_Hash)(nil), "chain.core.txdb.internal.storage.Mainchain.Hash")
	proto.RegisterType((*Rollback)(nil), "chain.core.txdb.internal.storage.Rollback")
	proto.RegisterType((*Rollback_Hash)(nil), "chain.core.txdb.internal.storage.Rollback.Hash")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x95, 0xfe, 0x7d, 0xcd, 0xf9, 0xa8, 0x84, 0x3c, 0x45, 0x61, 0x09, 0x9d, 0x32, 0x19,
	0x04, 0x4b, 0x67, 0x06, 0xe8, 0xd2, 0x0c, 0x2e, 0x13, 0x0b, 0x72, 0x92, 0x23, 0x1c, 0x35, 0xb5,
	0x23, 0xdb, 0x43, 0x3b, 0x72, 0x53, 0x5c, 0x1f, 0xb2, 0xe3, 0x20, 0x21, 0x81, 0x0a, 0x6c, 0xc7,
	0x47, 0x7e, 0x9e, 0xf7, 0x95, 0x65, 0x58, 0x18, 0xab, 0x34, 0x7f, 0x41, 0xda, 0x69, 0x65, 0x15,
	0xc9, 0x2a, 0xc1, 0x1b, 0x49, 0x2b, 0xa5, 0x91, 0xda, 0x43, 0x5d, 0xd2, 0x46, 0x5a, 0xd4, 0x92,
	0xb7, 0x34, 0xdc, 0x5b, 0xbe, 0x8e, 0x60, 0xbe, 0x95, 0xbc, 0x33, 0x42, 0x59, 0x52, 0xc0, 0x54,
	0xaa, 0x1a, 0x4d, 0x12, 0x65, 0xe3, 0xfc, 0xff, 0xcd, 0x8a, 0x9e, 0xc2, 0xe9, 0x80, 0xd2, 0xad,
	0xe5, 0x16, 0x1f, 0x35, 0x62, 0xa1, 0x6a, 0x64, 0xbd, 0x86, 0xac, 0x61, 0x26, 0x95, 0xac, 0xd0,
	0x24, 0x23, 0x2f, 0xbc, 0xfe, 0x85, 0xb0, 0x70, 0x20, 0x0b, 0x7c, 0xba, 0x82, 0xa9, 0x5f, 0x10,
	0x02, 0x13, 0xc1, 0x8d, 0x48, 0xa2, 0x2c, 0xca, 0xcf, 0x98, 0x9f, 0xc9, 0x05, 0xc4, 0x78, 0xe8,
	0x1a, 0x7d, 0x7c, 0xde, 0xbb, 0xa4, 0x28, 0x9f, 0xb0, 0x79, 0xbf, 0xd8, 0x98, 0xf4, 0x12, 0x16,
	0x9f, 0xba, 0x91, 0x73, 0x18, 0xef, 0xf0, 0x18, 0x04, 0x6e, 0x5c, 0xee, 0x21, 0xde, 0xf0, 0x46,
	0xfa, 0x6e, 0xe4, 0x1e, 0xa6, 0x4e, 0x3a, 0xbc, 0xc1, 0x0f, 0x2a, 0x7f, 0xb0, 0x74, 0xcd, 0x8d,
	0x60, 0x3d, 0x9e, 0x26, 0x30, 0x71, 0xc7, 0x2f, 0xe2, 0xde, 0x22, 0x98, 0x33, 0xd5, 0xb6, 0x25,
	0xaf, 0x76, 0xe4, 0x01, 0x66, 0x35, 0x5a, 0x5e, 0x89, 0x90, 0x77, 0x75, 0x3a, 0x6f, 0x60, 0xfb,
	0xb8, 0x80, 0x3b, 0x11, 0xb7, 0x5e, 0x34, 0xfa, 0xa3, 0xa8, 0xc7, 0xbf, 0x2f, 0x7e, 0x17, 0x3f,
	0xfd, 0x0b, 0x68, 0x39, 0xf3, 0xff, 0xeb, 0xf6, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x7d, 0x6c,
	0x84, 0x70, 0x02, 0x00, 0x00,
}
