// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

/*
Package storage is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	UtxoEntry
	Mainchain
*/
package storage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UtxoEntry struct {
	IsCoinBase  bool   `protobuf:"varint,1,opt,name=isCoinBase" json:"isCoinBase,omitempty"`
	BlockHeight uint64 `protobuf:"varint,2,opt,name=blockHeight" json:"blockHeight,omitempty"`
	Spend       bool   `protobuf:"varint,3,opt,name=spend" json:"spend,omitempty"`
}

func (m *UtxoEntry) Reset()                    { *m = UtxoEntry{} }
func (m *UtxoEntry) String() string            { return proto.CompactTextString(m) }
func (*UtxoEntry) ProtoMessage()               {}
func (*UtxoEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UtxoEntry) GetIsCoinBase() bool {
	if m != nil {
		return m.IsCoinBase
	}
	return false
}

func (m *UtxoEntry) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *UtxoEntry) GetSpend() bool {
	if m != nil {
		return m.Spend
	}
	return false
}

// Mainchain represents a mainchain of the blockchain
type Mainchain struct {
	Hashs []*Mainchain_Hash `protobuf:"bytes,1,rep,name=hashs" json:"hashs,omitempty"`
}

func (m *Mainchain) Reset()                    { *m = Mainchain{} }
func (m *Mainchain) String() string            { return proto.CompactTextString(m) }
func (*Mainchain) ProtoMessage()               {}
func (*Mainchain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Mainchain) GetHashs() []*Mainchain_Hash {
	if m != nil {
		return m.Hashs
	}
	return nil
}

type Mainchain_Hash struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Mainchain_Hash) Reset()                    { *m = Mainchain_Hash{} }
func (m *Mainchain_Hash) String() string            { return proto.CompactTextString(m) }
func (*Mainchain_Hash) ProtoMessage()               {}
func (*Mainchain_Hash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Mainchain_Hash) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
	proto.RegisterType((*UtxoEntry)(nil), "chain.core.txdb.internal.storage.UtxoEntry")
	proto.RegisterType((*Mainchain)(nil), "chain.core.txdb.internal.storage.Mainchain")
	proto.RegisterType((*Mainchain_Hash)(nil), "chain.core.txdb.internal.storage.Mainchain.Hash")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0x89, 0xbd, 0x53, 0xfb, 0x4e, 0x41, 0x82, 0x43, 0x70, 0x90, 0x70, 0x53, 0xa7, 0x87,
	0xe8, 0x7f, 0x70, 0xa2, 0xdc, 0xe2, 0x12, 0x70, 0x71, 0x4b, 0xd3, 0xd0, 0x84, 0xd6, 0xa4, 0x24,
	0x19, 0xda, 0xff, 0x5e, 0x9a, 0x16, 0xe9, 0x76, 0xdb, 0xfb, 0x3e, 0xde, 0x0f, 0x7e, 0x7c, 0x70,
	0x1f, 0x93, 0x0f, 0xb2, 0xd5, 0x38, 0x04, 0x9f, 0x3c, 0xe5, 0xca, 0x48, 0xeb, 0x50, 0xf9, 0xa0,
	0x31, 0x8d, 0x4d, 0x8d, 0xd6, 0x25, 0x1d, 0x9c, 0xec, 0x71, 0xfd, 0x3b, 0x2a, 0x28, 0xbf, 0xd3,
	0xe8, 0x3f, 0x5c, 0x0a, 0x13, 0x7d, 0x06, 0xb0, 0xf1, 0xdd, 0x5b, 0x77, 0x92, 0x51, 0x33, 0xc2,
	0x49, 0x75, 0x2b, 0x36, 0x0d, 0xe5, 0x70, 0xa8, 0x7b, 0xaf, 0xba, 0xb3, 0xb6, 0xad, 0x49, 0xec,
	0x8a, 0x93, 0x6a, 0x27, 0xb6, 0x15, 0x7d, 0x84, 0x7d, 0x1c, 0xb4, 0x6b, 0x58, 0x91, 0xe1, 0x25,
	0x1c, 0x7f, 0xa1, 0xfc, 0x92, 0xd6, 0x65, 0x19, 0xfa, 0x09, 0x7b, 0x23, 0xa3, 0x89, 0x8c, 0xf0,
	0xa2, 0x3a, 0xbc, 0xbe, 0xe0, 0x25, 0x47, 0xfc, 0x67, 0xf1, 0x2c, 0xa3, 0x11, 0x0b, 0xfe, 0xc4,
	0x60, 0x37, 0x47, 0xfa, 0x00, 0x45, 0xa7, 0xa7, 0x6c, 0x7b, 0x27, 0xe6, 0xf3, 0x54, 0xfe, 0xdc,
	0xac, 0x68, 0x7d, 0x9d, 0x77, 0x78, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x3e, 0xf1, 0xc4,
	0x18, 0x01, 0x00, 0x00,
}
